# Generated by Django 4.1.2 on 2022-10-08 01:03

import calificaciones.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='valor',
            field=models.IntegerField(validators=[calificaciones.validators.validar_calificacion]),
        ),
    ]
